language: node_js
os: linux
sudo: true
node_js:
- '11'
branches:
  only:
  - master
install:
- npm i
script:
- npm run build
addons:
  ssh_known_hosts: raimondlu.me
before_deploy:
- openssl aes-256-cbc -K $encrypted_7efe786a4d1f_key -iv $encrypted_7efe786a4d1f_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -chavzP dist/* $SSH_USERNAME@raimondlu.me>:/var/www/raimondlu.me/fuud
  on:
    branch: master
